version: "3"

services:
  app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8-alpine3.10
    container_name: docker-nginx-gunicorn-uvicorn_app
    restart: unless-stopped
    volumes:
      - ./app:/app
    networks:
      network:
        ipv4_address: "172.35.0.2"
    environment:
      - HOST=172.35.0.2
      - PORT=80
    entrypoint: /start-reload.sh
  webserver:
    image: nginx:1.19-alpine
    container_name: docker-nginx-gunicorn-uvicorn_webserver
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    networks:
      network:
        ipv4_address: "172.35.0.3"
    environment:
      - GUNICORN_HOST=172.35.0.2
      - GUNICORN_PORT=80
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "172.35.0.0/28"
